name: Build Release

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '**'

env:
  packageName: "nadena.dev.ndmf"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check semver syntax
        id: semver-check
        if: startsWith(github.ref, 'refs/tags/')
        env:
          REF_NAME: ${{ github.ref }}
        run: |
          if echo $REF_NAME | grep '[a-z]-[0-9]' && ! echo $REF_NAME | grep '^refs/tags/1\.5\.0-'; then
            echo "Tag name does not follow semver prerelease syntax: $REF_NAME"
            exit 1
          fi

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@a5a9c668b16513c737c3e1f8956772c99c73f6e8
        with:
          path: "package.json"
          prop_path: "version"

      - name: Check tag consistency
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          if [ "${{ steps.version.outputs.prop }}" != "${GITHUB_REF##*/}" ]; then
            echo "Version in package.json does not match tag name: ${{ steps.version.outputs.prop }} != ${GITHUB_REF##*/}"
            exit 1
          fi

      - run: echo ${{steps.version.outputs.prop}}

      - name: Set Environment Variables
        run: |
          echo "zipFile=${{ env.packageName }}-${{ steps.version.outputs.prop }}".zip >> $GITHUB_ENV
          echo "unityPackage=${{ env.packageName }}-${{ steps.version.outputs.prop }}.unitypackage" >> $GITHUB_ENV

      - name: Create Zip
        uses: thedoctor0/zip-release@a24011d8d445e4da5935a7e73c1f98e22a439464
        with:
          type: "zip"
          directory: "."
          filename: ".github/${{env.zipFile}}" # make the zip file two directories up, since we start two directories in above
          exclusions: '.github .git* *~ .gitignore *.ps1*'

      - name: Move zipfile
        run: |
          mv .github/${{env.zipFile}} ${{env.zipFile}}

      - uses: actions/upload-artifact@v3
        with:
          name: package-zip
          path: ${{ env.zipFile }}

      - name: Make Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          generate_release_notes: true
          tag_name: ${{ steps.version.outputs.prop }}
          files: |
            ${{ env.zipFile }}
            package.json
